#!/bin/bash
#SBATCH --job-name=rcv1bin
#SBATCH --output=rcvc1bin

#SBATCH --nodes=4 #number of nodes requested
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=3
#SBATCH --mem=50g
#SBATCH --partition=ib # opa, ib
#SBATCH --cluster=mpi # cluster name is required
#SBATCH --mail-user=an.xu@pitt.edu #send email to this address if ...
#SBATCH --mail-type=END,FAIL # ... job ends or fails
#SBATCH --time=4-00:00 # 4 days walltime in dd-hh:mm format
#SBATCH --qos=long # required if walltime is greater than 3 days

module purge
module load openmpi/3.1.1 gcc/5.4.0 cmake/3.13.3 mkl/2019.4 lapack/3.8.0 openmpi/3.1.1
mpirun -np $SLURM_NTASKS ./bin/afd \
    --reg 1e-4 --eta 0.05 \
    --d 47236 --n_train 677399 --n_test 20242 \
    --inner 677399 --save_interval 677399 --save_num 10 \
    --model 0 --method 1 --sync 0 --delay_fraction 0.2 \
    --train_data "/ihome/hhuang/anx6/datasets/rcv1_test_binary" \
    --test_data "/ihome/hhuang/anx6/datasets/rcv1_train_binary"
